
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `YOYOHRMS`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=YOYOHR;Persist Security Info=True;User ID=sa;password=**zapped**;MultipleActiveResultSets=True`
//     Schema:                 ``
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace YOYO.HRMS.Models
{
	public partial class YOYOHRMSDB : Database
	{
		public YOYOHRMSDB() 
			: base("YOYOHRMS")
		{
			CommonConstruct();
		}

		public YOYOHRMSDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			YOYOHRMSDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static YOYOHRMSDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new YOYOHRMSDB();
        }

		[ThreadStatic] static YOYOHRMSDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        
		public class Record<T> where T:new()
		{
			public static YOYOHRMSDB repo { get { return YOYOHRMSDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }
			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }
			
			private Dictionary<string,bool> ModifiedColumns;
			private void OnLoaded()
			{
				ModifiedColumns = new Dictionary<string,bool>();
			}
			protected void MarkColumnModified(string column_name)
			{
				if (ModifiedColumns!=null)
					ModifiedColumns[column_name]=true;
			}
			public int Update() 
			{ 
				if (ModifiedColumns==null)
					return repo.Update(this); 

				int retv = repo.Update(this, ModifiedColumns.Keys);
				ModifiedColumns.Clear();
				return retv;
			}
			public void Save() 
			{ 
				if (repo.IsNew(this))
					repo.Insert(this);
				else
					Update();
			}
		}
	}
	

    
	[TableName("TB_LocalizedTypes")]
	[PrimaryKey("C_ID")]
	[ExplicitColumns]
    public partial class LocalizedType : YOYOHRMSDB.Record<LocalizedType>  
    {
        [Column("C_ID")] 
		public long ID 
		{ 
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
				MarkColumnModified("C_ID");
			}
		}
		private long _ID;

        [Column("C_LocaleId")] 
		public int LocaleId 
		{ 
			get
			{
				return _LocaleId;
			}
			set
			{
				_LocaleId = value;
				MarkColumnModified("C_LocaleId");
			}
		}
		private int _LocaleId;

        [Column("c_key")] 
		public string Key 
		{ 
			get
			{
				return _Key;
			}
			set
			{
				_Key = value;
				MarkColumnModified("c_key");
			}
		}
		private string _Key;

        [Column("c_TypeName")] 
		public string TypeName 
		{ 
			get
			{
				return _TypeName;
			}
			set
			{
				_TypeName = value;
				MarkColumnModified("c_TypeName");
			}
		}
		private string _TypeName;

        [Column("c_TextName")] 
		public string TextName 
		{ 
			get
			{
				return _TextName;
			}
			set
			{
				_TextName = value;
				MarkColumnModified("c_TextName");
			}
		}
		private string _TextName;

        [Column("c_TextValue")] 
		public string TextValue 
		{ 
			get
			{
				return _TextValue;
			}
			set
			{
				_TextValue = value;
				MarkColumnModified("c_TextValue");
			}
		}
		private string _TextValue;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_LocalizedViews")]
	[PrimaryKey("C_ID")]
	[ExplicitColumns]
    public partial class LocalizedView : YOYOHRMSDB.Record<LocalizedView>  
    {
        [Column("C_ID")] 
		public long ID 
		{ 
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
				MarkColumnModified("C_ID");
			}
		}
		private long _ID;

        [Column("C_LocaleId")] 
		public int LocaleId 
		{ 
			get
			{
				return _LocaleId;
			}
			set
			{
				_LocaleId = value;
				MarkColumnModified("C_LocaleId");
			}
		}
		private int _LocaleId;

        [Column("c_key")] 
		public string Key 
		{ 
			get
			{
				return _Key;
			}
			set
			{
				_Key = value;
				MarkColumnModified("c_key");
			}
		}
		private string _Key;

        [Column("c_ViewPath")] 
		public string ViewPath 
		{ 
			get
			{
				return _ViewPath;
			}
			set
			{
				_ViewPath = value;
				MarkColumnModified("c_ViewPath");
			}
		}
		private string _ViewPath;

        [Column("c_TextName")] 
		public string TextName 
		{ 
			get
			{
				return _TextName;
			}
			set
			{
				_TextName = value;
				MarkColumnModified("c_TextName");
			}
		}
		private string _TextName;

        [Column("c_TextValue")] 
		public string TextValue 
		{ 
			get
			{
				return _TextValue;
			}
			set
			{
				_TextValue = value;
				MarkColumnModified("c_TextValue");
			}
		}
		private string _TextValue;

        [Column("c_CorporateID")] 
		public long CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_Module")]
	[PrimaryKey("c_MouduleID")]
	[ExplicitColumns]
    public partial class Module : YOYOHRMSDB.Record<Module>  
    {
        [Column("c_MouduleID")] 
		public long MouduleID 
		{ 
			get
			{
				return _MouduleID;
			}
			set
			{
				_MouduleID = value;
				MarkColumnModified("c_MouduleID");
			}
		}
		private long _MouduleID;

        [Column("c_RoleCode")] 
		public string RoleCode 
		{ 
			get
			{
				return _RoleCode;
			}
			set
			{
				_RoleCode = value;
				MarkColumnModified("c_RoleCode");
			}
		}
		private string _RoleCode;

        [Column("c_Description")] 
		public string Description 
		{ 
			get
			{
				return _Description;
			}
			set
			{
				_Description = value;
				MarkColumnModified("c_Description");
			}
		}
		private string _Description;

        [Column("c_LinkURL")] 
		public string LinkURL 
		{ 
			get
			{
				return _LinkURL;
			}
			set
			{
				_LinkURL = value;
				MarkColumnModified("c_LinkURL");
			}
		}
		private string _LinkURL;

        [Column("c_IsMenu")] 
		public bool? IsMenu 
		{ 
			get
			{
				return _IsMenu;
			}
			set
			{
				_IsMenu = value;
				MarkColumnModified("c_IsMenu");
			}
		}
		private bool? _IsMenu;

        [Column("c_IsLeaf")] 
		public bool? IsLeaf 
		{ 
			get
			{
				return _IsLeaf;
			}
			set
			{
				_IsLeaf = value;
				MarkColumnModified("c_IsLeaf");
			}
		}
		private bool? _IsLeaf;

        [Column("c_ParentID")] 
		public long? ParentID 
		{ 
			get
			{
				return _ParentID;
			}
			set
			{
				_ParentID = value;
				MarkColumnModified("c_ParentID");
			}
		}
		private long? _ParentID;

        [Column("c_SortNo")] 
		public int? SortNo 
		{ 
			get
			{
				return _SortNo;
			}
			set
			{
				_SortNo = value;
				MarkColumnModified("c_SortNo");
			}
		}
		private int? _SortNo;

        [Column("c_ControlName")] 
		public string ControlName 
		{ 
			get
			{
				return _ControlName;
			}
			set
			{
				_ControlName = value;
				MarkColumnModified("c_ControlName");
			}
		}
		private string _ControlName;

        [Column("c_IsEnabled")] 
		public bool? IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool? _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_ModulePriviledge")]
	[PrimaryKey("c_ModulePriviledgeID")]
	[ExplicitColumns]
    public partial class ModulePriviledge : YOYOHRMSDB.Record<ModulePriviledge>  
    {
        [Column("c_ModulePriviledgeID")] 
		public long ModulePriviledgeID 
		{ 
			get
			{
				return _ModulePriviledgeID;
			}
			set
			{
				_ModulePriviledgeID = value;
				MarkColumnModified("c_ModulePriviledgeID");
			}
		}
		private long _ModulePriviledgeID;

        [Column("c_PriviledgeID")] 
		public long PriviledgeID 
		{ 
			get
			{
				return _PriviledgeID;
			}
			set
			{
				_PriviledgeID = value;
				MarkColumnModified("c_PriviledgeID");
			}
		}
		private long _PriviledgeID;

        [Column("c_MouduleID")] 
		public long MouduleID 
		{ 
			get
			{
				return _MouduleID;
			}
			set
			{
				_MouduleID = value;
				MarkColumnModified("c_MouduleID");
			}
		}
		private long _MouduleID;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_Priviledge")]
	[PrimaryKey("c_PriviledgeID")]
	[ExplicitColumns]
    public partial class Priviledge : YOYOHRMSDB.Record<Priviledge>  
    {
        [Column("c_PriviledgeID")] 
		public long PriviledgeID 
		{ 
			get
			{
				return _PriviledgeID;
			}
			set
			{
				_PriviledgeID = value;
				MarkColumnModified("c_PriviledgeID");
			}
		}
		private long _PriviledgeID;

        [Column("c_PriviledgeName")] 
		public string PriviledgeName 
		{ 
			get
			{
				return _PriviledgeName;
			}
			set
			{
				_PriviledgeName = value;
				MarkColumnModified("c_PriviledgeName");
			}
		}
		private string _PriviledgeName;

        [Column("c_PriviledgeDesc")] 
		public string PriviledgeDesc 
		{ 
			get
			{
				return _PriviledgeDesc;
			}
			set
			{
				_PriviledgeDesc = value;
				MarkColumnModified("c_PriviledgeDesc");
			}
		}
		private string _PriviledgeDesc;

        [Column("c_ControlName")] 
		public string ControlName 
		{ 
			get
			{
				return _ControlName;
			}
			set
			{
				_ControlName = value;
				MarkColumnModified("c_ControlName");
			}
		}
		private string _ControlName;

        [Column("c_ActionName")] 
		public string ActionName 
		{ 
			get
			{
				return _ActionName;
			}
			set
			{
				_ActionName = value;
				MarkColumnModified("c_ActionName");
			}
		}
		private string _ActionName;

        [Column("c_IsButton")] 
		public bool? IsButton 
		{ 
			get
			{
				return _IsButton;
			}
			set
			{
				_IsButton = value;
				MarkColumnModified("c_IsButton");
			}
		}
		private bool? _IsButton;

        [Column("c_ParentID")] 
		public long? ParentID 
		{ 
			get
			{
				return _ParentID;
			}
			set
			{
				_ParentID = value;
				MarkColumnModified("c_ParentID");
			}
		}
		private long? _ParentID;

        [Column("c_SortNo")] 
		public int? SortNo 
		{ 
			get
			{
				return _SortNo;
			}
			set
			{
				_SortNo = value;
				MarkColumnModified("c_SortNo");
			}
		}
		private int? _SortNo;

        [Column("c_IsEnabled")] 
		public bool? IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool? _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_PriviledgeGranted")]
	[PrimaryKey("c_GrantID")]
	[ExplicitColumns]
    public partial class PriviledgeGranted : YOYOHRMSDB.Record<PriviledgeGranted>  
    {
        [Column("c_GrantID")] 
		public long GrantID 
		{ 
			get
			{
				return _GrantID;
			}
			set
			{
				_GrantID = value;
				MarkColumnModified("c_GrantID");
			}
		}
		private long _GrantID;

        [Column("c_ModulePriviledgeID")] 
		public long ModulePriviledgeID 
		{ 
			get
			{
				return _ModulePriviledgeID;
			}
			set
			{
				_ModulePriviledgeID = value;
				MarkColumnModified("c_ModulePriviledgeID");
			}
		}
		private long _ModulePriviledgeID;

        [Column("c_GrantType")] 
		public bool? GrantType 
		{ 
			get
			{
				return _GrantType;
			}
			set
			{
				_GrantType = value;
				MarkColumnModified("c_GrantType");
			}
		}
		private bool? _GrantType;

        [Column("c_UserRoleID")] 
		public long? UserRoleID 
		{ 
			get
			{
				return _UserRoleID;
			}
			set
			{
				_UserRoleID = value;
				MarkColumnModified("c_UserRoleID");
			}
		}
		private long? _UserRoleID;

        [Column("c_BeginDate")] 
		public DateTime? BeginDate 
		{ 
			get
			{
				return _BeginDate;
			}
			set
			{
				_BeginDate = value;
				MarkColumnModified("c_BeginDate");
			}
		}
		private DateTime? _BeginDate;

        [Column("c_EndDate")] 
		public DateTime? EndDate 
		{ 
			get
			{
				return _EndDate;
			}
			set
			{
				_EndDate = value;
				MarkColumnModified("c_EndDate");
			}
		}
		private DateTime? _EndDate;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_Role")]
	[PrimaryKey("c_RoleID")]
	[ExplicitColumns]
    public partial class Role : YOYOHRMSDB.Record<Role>  
    {
        [Column("c_RoleID")] 
		public long RoleID 
		{ 
			get
			{
				return _RoleID;
			}
			set
			{
				_RoleID = value;
				MarkColumnModified("c_RoleID");
			}
		}
		private long _RoleID;

        [Column("c_RoleCode")] 
		public string RoleCode 
		{ 
			get
			{
				return _RoleCode;
			}
			set
			{
				_RoleCode = value;
				MarkColumnModified("c_RoleCode");
			}
		}
		private string _RoleCode;

        [Column("c_RoleName")] 
		public string RoleName 
		{ 
			get
			{
				return _RoleName;
			}
			set
			{
				_RoleName = value;
				MarkColumnModified("c_RoleName");
			}
		}
		private string _RoleName;

        [Column("c_IsEnabled")] 
		public bool IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_SysLang")]
	[PrimaryKey("c_LanID")]
	[ExplicitColumns]
    public partial class SysLang : YOYOHRMSDB.Record<SysLang>  
    {
        [Column("c_LanID")] 
		public long LanID 
		{ 
			get
			{
				return _LanID;
			}
			set
			{
				_LanID = value;
				MarkColumnModified("c_LanID");
			}
		}
		private long _LanID;

        [Column("c_LocaleID")] 
		public int LocaleID 
		{ 
			get
			{
				return _LocaleID;
			}
			set
			{
				_LocaleID = value;
				MarkColumnModified("c_LocaleID");
			}
		}
		private int _LocaleID;

        [Column("c_LocaleCode")] 
		public string LocaleCode 
		{ 
			get
			{
				return _LocaleCode;
			}
			set
			{
				_LocaleCode = value;
				MarkColumnModified("c_LocaleCode");
			}
		}
		private string _LocaleCode;

        [Column("c_LocaleName")] 
		public string LocaleName 
		{ 
			get
			{
				return _LocaleName;
			}
			set
			{
				_LocaleName = value;
				MarkColumnModified("c_LocaleName");
			}
		}
		private string _LocaleName;

        [Column("Locale_ID")] 
		public int ID 
		{ 
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
				MarkColumnModified("Locale_ID");
			}
		}
		private int _ID;

        [Column("Locale_Code")] 
		public string Code 
		{ 
			get
			{
				return _Code;
			}
			set
			{
				_Code = value;
				MarkColumnModified("Locale_Code");
			}
		}
		private string _Code;

        [Column("Locale_Name")] 
		public string Name 
		{ 
			get
			{
				return _Name;
			}
			set
			{
				_Name = value;
				MarkColumnModified("Locale_Name");
			}
		}
		private string _Name;

        [Column("c_CorporateID")] 
		public long CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long _CorporateID;

	}
    
	[TableName("TB_User")]
	[PrimaryKey("c_UserID")]
	[ExplicitColumns]
    public partial class User : YOYOHRMSDB.Record<User>  
    {
        [Column("c_UserID")] 
		public long UserID 
		{ 
			get
			{
				return _UserID;
			}
			set
			{
				_UserID = value;
				MarkColumnModified("c_UserID");
			}
		}
		private long _UserID;

        [Column("c_UserCode")] 
		public string UserCode 
		{ 
			get
			{
				return _UserCode;
			}
			set
			{
				_UserCode = value;
				MarkColumnModified("c_UserCode");
			}
		}
		private string _UserCode;

        [Column("c_UserName")] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("c_UserName");
			}
		}
		private string _UserName;

        [Column("c_UserPwd")] 
		public string UserPwd 
		{ 
			get
			{
				return _UserPwd;
			}
			set
			{
				_UserPwd = value;
				MarkColumnModified("c_UserPwd");
			}
		}
		private string _UserPwd;

        [Column("c_MailAddress")] 
		public string MailAddress 
		{ 
			get
			{
				return _MailAddress;
			}
			set
			{
				_MailAddress = value;
				MarkColumnModified("c_MailAddress");
			}
		}
		private string _MailAddress;

        [Column("c_IsAdmin")] 
		public bool IsAdmin 
		{ 
			get
			{
				return _IsAdmin;
			}
			set
			{
				_IsAdmin = value;
				MarkColumnModified("c_IsAdmin");
			}
		}
		private bool _IsAdmin;

        [Column("c_IsEnabled")] 
		public bool IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

	}
    
	[TableName("TB_UserRole")]
	[PrimaryKey("c_UserRoleID")]
	[ExplicitColumns]
    public partial class UserRole : YOYOHRMSDB.Record<UserRole>  
    {
        [Column("c_UserRoleID")] 
		public long UserRoleID 
		{ 
			get
			{
				return _UserRoleID;
			}
			set
			{
				_UserRoleID = value;
				MarkColumnModified("c_UserRoleID");
			}
		}
		private long _UserRoleID;

        [Column("c_UserID")] 
		public long? UserID 
		{ 
			get
			{
				return _UserID;
			}
			set
			{
				_UserID = value;
				MarkColumnModified("c_UserID");
			}
		}
		private long? _UserID;

        [Column("c_RoleID")] 
		public long? RoleID 
		{ 
			get
			{
				return _RoleID;
			}
			set
			{
				_RoleID = value;
				MarkColumnModified("c_RoleID");
			}
		}
		private long? _RoleID;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_Corporate")]
	[PrimaryKey("c_CorporateID", autoIncrement=false)]
	[ExplicitColumns]
    public partial class Corporate : YOYOHRMSDB.Record<Corporate>  
    {
        [Column("c_CorporateID")] 
		public long CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long _CorporateID;

        [Column("c_CorporateCode")] 
		public string CorporateCode 
		{ 
			get
			{
				return _CorporateCode;
			}
			set
			{
				_CorporateCode = value;
				MarkColumnModified("c_CorporateCode");
			}
		}
		private string _CorporateCode;

        [Column("c_CorporateName")] 
		public string CorporateName 
		{ 
			get
			{
				return _CorporateName;
			}
			set
			{
				_CorporateName = value;
				MarkColumnModified("c_CorporateName");
			}
		}
		private string _CorporateName;

        [Column("c_IsEnabled")] 
		public bool IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
    
	[TableName("TB_UserCorporatePriv")]
	[PrimaryKey("c_PrivID", autoIncrement=false)]
	[ExplicitColumns]
    public partial class UserCorporatePriv : YOYOHRMSDB.Record<UserCorporatePriv>  
    {
        [Column("c_PrivID")] 
		public long PrivID 
		{ 
			get
			{
				return _PrivID;
			}
			set
			{
				_PrivID = value;
				MarkColumnModified("c_PrivID");
			}
		}
		private long _PrivID;

        [Column("c_UserID")] 
		public long? UserID 
		{ 
			get
			{
				return _UserID;
			}
			set
			{
				_UserID = value;
				MarkColumnModified("c_UserID");
			}
		}
		private long? _UserID;

        [Column("c_CorporateID")] 
		public long? CorporateID 
		{ 
			get
			{
				return _CorporateID;
			}
			set
			{
				_CorporateID = value;
				MarkColumnModified("c_CorporateID");
			}
		}
		private long? _CorporateID;

        [Column("c_IsEnabled")] 
		public bool IsEnabled 
		{ 
			get
			{
				return _IsEnabled;
			}
			set
			{
				_IsEnabled = value;
				MarkColumnModified("c_IsEnabled");
			}
		}
		private bool _IsEnabled;

        [Column("c_IsDeleted")] 
		public bool? IsDeleted 
		{ 
			get
			{
				return _IsDeleted;
			}
			set
			{
				_IsDeleted = value;
				MarkColumnModified("c_IsDeleted");
			}
		}
		private bool? _IsDeleted;

        [Column("c_Created")] 
		public string Created 
		{ 
			get
			{
				return _Created;
			}
			set
			{
				_Created = value;
				MarkColumnModified("c_Created");
			}
		}
		private string _Created;

        [Column("c_CreatDate")] 
		public DateTime? CreatDate 
		{ 
			get
			{
				return _CreatDate;
			}
			set
			{
				_CreatDate = value;
				MarkColumnModified("c_CreatDate");
			}
		}
		private DateTime? _CreatDate;

        [Column("c_Updated")] 
		public string Updated 
		{ 
			get
			{
				return _Updated;
			}
			set
			{
				_Updated = value;
				MarkColumnModified("c_Updated");
			}
		}
		private string _Updated;

        [Column("c_UpdateDate")] 
		public DateTime? UpdateDate 
		{ 
			get
			{
				return _UpdateDate;
			}
			set
			{
				_UpdateDate = value;
				MarkColumnModified("c_UpdateDate");
			}
		}
		private DateTime? _UpdateDate;

	}
}


